# Generated by Django 2.2.9 on 2020-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
